[package]
name = "naf_calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
bytes = "1.1.0"
libmath = "0.2.1"
r2d2_sqlite = "0.19.0"
r2d2 = "0.8.9"
# libsqlite3-sys = "0.23.2"
rusqlite = { version = "0.26.3", features = ["bundled"] }
yaml-rust = "0.4"
encoding = "0.2"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
dirs-next = "2.0.0"
druid = "0.7.0"

[dependencies.windows]
version = "0.32.0"
features = [
    "alloc",
 #   "Data_Xml_Dom",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_UI_WindowsAndMessaging",
]